version: "3"

services:
  api:
    build:
      context: .
    environment:
      # SQLALCHEMY_DATABASE_URI: mysql://root:password@mariadb/test
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@postgres/test
      SIMULATE_NETWORK_LATENCY: "true"
    volumes:
      - .:/src
    ports:
      - 8000:8000
    restart: always

  mariadb:
    image: mariadb:10.3.27
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
